### ISSUE TITLE
Dependency on Dart Mirrors

### ISSUE THREAD

**Issue by joeblew99** [stevenroose/dart-eventsource#12]
I saw this here in your code:
https://github.com/stevenroose/dart-eventsource/blob/master/example/client_browser.dart#L5

The issue is closed though.

SO is the comment in the code still relevent ?
It seems not ?
https://github.com/dart-lang/http/pull/55

SO then the Comment is not defunct ?

**Comment by stevenroose** [comment]
I haven't worked on this for several years. I don't know if the special browser_client is still needed. If you can confirm that it's deprecated and you can create an EventSource using the default import on browsers, you can make a PR to remove it.

**Comment by joeblew99** [comment]
Ok thanks.
Will try it out in flutter web
