### ISSUE TITLE
Dart 2 - Not a subtype error

### ISSUE THREAD

**Issue by jspschool** [stevenroose/dart-eventsource#6]
I use Dart VM version: 2.1.0-dev.9.4.flutter-f9ebf21297

I think dart does not match type

Unhandled exception:
type '(Duration) => void' is not a subtype of type '(dynamic) => void'
#0      new EventSource._internal (package:eventsource/eventsource.dart:69:55)
#1      EventSource.connect (package:eventsource/eventsource.dart:63:26)

**Comment by stevenroose** [comment]
Why did you close this, was this solved?
